[package]
name = "trainingsapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
serde = "1.0.156"
mongodb = "2.3.0"
tokio = "1"
argon2 = "0.5.0"
